### ISSUE TITLE
tramp support?

### ISSUE THREAD

**Issue by xwl** [10sr/git-command-el#11]
When editing a remote file via tramp ssh (e.g., a buffer named /ssh:xwl@kirsche.local:/foo.cpp), for instance, do you have plan to support the tramp?

Right now, it would error:

```
fatal: Not a git repository (or any of the parent directories): .git

Process term-/bin/bash exited abnormally with code 128
```

**Comment by 10sr** [comment]
Thanks!

I personally do not use tramp, so I'm sorry to say I do not have a motivation to support tramp currently...
